services:
  golang:
    image: golang@sha256:30baaea08c5d1e858329c50f29fe381e9b7d7bced11a0f5f1f69a1504cdfbf5e
    volumes:
      - .:/code
    working_dir: /code

  skillistry-bff:
    build:
      context: ./src
      dockerfile: ./docker/dockerfile
      args:
         - project_controller=controller.go
    ports: 
      - "8080:8080"
